version: "3.8"
services:
  envoy-config-dev:
    build: .devcontainer
    tty: true
    container_name: envoy-config-dev
    volumes:
      - .:/src/:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    environment:
      TZ: Asia/Tokyo
    networks:
      - envoy-net
networks:
  default:
    name: bridge
  envoy-net:
    name: envoy-net
    driver: bridge
